### PR TITLE
fix and improve readability of the get view

### PR DESCRIPTION
**Pull request by yoniLavi**
(based on feedback by Jon Hill)

In the GET view, add the missing default value for the pk, and improve readability by reordering the logic.

### CODE REVIEW

**Comment by yoniLavi** [comment]
P.S.
Once this is integrated, we'd need to update the "User Authentication" unit accordingly

**Comment by aaronsnig501** [comment]
@yoniLavi Could ask that you address the PEP8 issues outlined above before I merge this in? Thanks

**Comment by aaronsnig501** [comment]
I think we'll need to upgrade to this soon - http://www.django-rest-framework.org/topics/3.6-announcement/

**Comment by yoniLavi** [comment]
@aaronsnig501 , I ran a massive autopep8 change to fix all these issues, and even added that AUTH_PASSWORD_VALIDATORS on top of that :)

Also fixed a few minor other issues on the way, and removed an accidentally (I assume) committed env directory.

Concerning updating to the new version, maybe, but that's a whole `nother story :)

**Comment by yoniLavi** [comment]
damn, I accidentally merged it myself. I rolled back the push now, but there's no way to reopen this pull request, so I'll create a new one

**Pull request merged**
